### ISSUE TITLE
duplicate of the function "get_neighbours"

### ISSUE THREAD

**Issue by stripey-tiger** [freude/NanoNet#50]
why are there two copies of this function? i have highlighted the second copy, which is superfluous (see below)

https://github.com/freude/NanoNet/blob/c9805d550d28d3684cdce8c8ab40903d0bfa45e2/tb/structure_designer.py#L46-L69

**Comment by freude** [comment]
On is to find neighbors for an isolated structure without periodic translation. Another works for finding neighbors across interfaces. Since they look almost the same, it is not the best code style. So I am going to refactor classes StructureDesigner and CyclicTopology to make them sharing the function get_neighbours(). Probably one class should inherit this function from another. In any case, I am agree the code is not optimal here and has to be fixed.

**Comment by freude** [comment]
The issue is solved
